[tool.poetry]
name = "olas-agent"
version = "0.1.0"
description = ""
authors = ["Jovan Mwesigwa  <jovanmwesigwa79@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mech-client = "^0.2.14"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"

[tool.poetry.scripts]
start = "main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
